### ISSUE TITLE
[BUG] Weird fatal error on kill

### ISSUE THREAD

**Issue by MrBlasyMSK** [ErikPDev/AdvanceDeaths#29]
**Describe the bug**
When you kill someone, there is a small error in the console

**To Reproduce**
Kill someone in the dev130
See the error in the console, but it doesnt crash

**Expected behavior**
Dont display nothing in the console, only the kill

**Screenshots or Crash Dump**
```
[Server thread/INFO]: UnMamaHuevo was slain by MrBlasyMSK

Fatal error: Uncaught ErrorException: include(phar:///home/container/plugins/AdvanceDeaths_dev-127.phar/src/ErikPDev/AdvanceDeaths/libs/poggit/libasynql/result/SqlInsertResult.php): Failed to open stream: phar error: Cannot open phar archive "/home/container/plugins/AdvanceDeaths_dev-127.phar" for reading in phar:///home/container/PocketMine-MP.phar/vendor/pocketmine/classloader/src/BaseClassLoader.php:93
Stack trace:
#0 phar:///home/container/PocketMine-MP.phar/vendor/pocketmine/classloader/src/BaseClassLoader.php(93): pocketmine\errorhandler\ErrorToExceptionHandler::handle(2, 'include(phar://...', 'phar:///home/co...', 93)
#1 phar:///home/container/PocketMine-MP.phar/vendor/pocketmine/classloader/src/BaseClassLoader.php(93): include()
#2 phar:///home/container/PocketMine-MP.phar/vendor/pocketmine/classloader/src/BaseClassLoader.php(83): BaseClassLoader->loadClass('ErikPDev\\Advanc...')
#3 phar:///home/container/plugins/AdvanceDeaths_dev-127.phar/src/ErikPDev/AdvanceDeaths/libs/poggit/libasynql/sqlite3/Sqlite3Thread.php(105): BaseClassLoader->{closure}('ErikPDev\\Advanc...')
#4 phar:///home/container/plugins/AdvanceDeaths_dev-127.phar/src/ErikPDev/AdvanceDeaths/libs/poggit/libasynql/base/SqlSlaveThread.php(88): ErikPDev\AdvanceDeaths\libs\poggit\libasynql\sqlite3\Sqlite3Thread->executeQuery(Object(SQLite3), 2, 'INSERT OR REPLA...', Array)
#5 phar:///home/container/PocketMine-MP.phar/src/thread/CommonThreadPartsTrait.php(93): ErikPDev\AdvanceDeaths\libs\poggit\libasynql\base\SqlSlaveThread->onRun()
#6 [internal function]: pocketmine\thread\Thread->run()
#7 {main}
  thrown in phar:///home/container/PocketMine-MP.phar/vendor/pocketmine/classloader/src/BaseClassLoader.php on line 93
  ```

**Device Information**
 - OS: Android 11 / Windows10
 - Minecraft Version: 1.18.12
 
**Server Information (please complete the following information):**
 - OS: linux
 - PMMP Version: 4.2.5 [Protocol 486]
 - PHP Version: 8.0.17

**Additional context**
X

**Comment by MrBlasyMSK** [comment]
oh wait it says dev127 in the plugin

**Comment by MrBlasyMSK** [comment]
Mb its fixed in the dev 130

**Comment by ErikPDev** [comment]
:p

**Comment by ErikPDev** [comment]
Just adding extra information, it seems the deathEvent is called but the AdvanceDeaths phar is removed.
